POST http://localhost:3000/user/register
Content-Type: application/json

{
    "firstname": "asl;kjasdf",
    "lastname": "yess",
    "email": "person@asdfyess.com",
    "password": "personpassword1234"
}

###

POST http://localhost:3000/products/product/
Content-Type: application/json

{
    "title": "amd 5700xt",
    "description": "fastest gpu*",
    "price": 23000,
    "qty": 6
}

###

GET http://localhost:3000/products/products/


###
POST http://localhost:3000/user/login 
Content-Type: application/json

{
    "email" : "e@mail.com",
    "password": "asdfasdf"
}

###

POST http://localhost:3000/user/register 
Content-Type: application/json

{
    "firstname": "fname",
    "lastname": "lname",
    "email": "e@mail.com",
    "password": "asdfasdf"
}