POST http://localhost:3000/api/register
Content-Type: application/json

{
    "firstname": "no",
    "lastname": "yess",
    "email": "person@fyess.com",
    "password": "11111111"
}

###

POST http://localhost:3000/api/product/
Content-Type: application/json

{
    "title": "ASUS ROG Strix Z490-E Gaming",
    "brand": "ASUS",
    "description": "Advanced motherboard for gaming and overclocking",
    "price": 28000,
    "qty": 8
}

###

GET http://localhost:3000/api/products/


###
POST http://localhost:3000/api/login 
Content-Type: application/json

{
    "email" : "e@mail.com",
    "password": "asdfasdf"
}

###
GET  http://localhost:3000/api/product/66700639e99b021f5d2f9e16

###

PUT http://localhost:3000/api/cart/update/
Content-Type: application/json
 
{
    "userId": "667172b7402a5aa71991b574",
    "productId": "66700685e99b021f5d2f9e22",
    "qty" : 5
}
